name: bricks_and_cli

packages:
  - vyuh_cli

ide:
  intellij:
    moduleNamePrefix: ''

scripts:
  update_version:
    run: dart run tools/update_version.dart

command:
  version:
    hooks:
      post: melos run update_version
