#!/usr/bin/env just --justfile

# Note: Make sure to re-genrate bundles if the bricks are modified.

# Bundle vyuh_init template
bundle-init:
    mason bundle ../vyuh_init -t dart -o lib/src/commands/create/templates/project

# Bundle vyuh_feature template
bundle-feature:
    mason bundle ../vyuh_feature -t dart -o lib/src/commands/create/templates/feature

# Bundle vyuh_feature_sanity_schema template
bundle-feature-sanity:
    mason bundle ../vyuh_feature_sanity_schema -t dart -o lib/src/commands/create/templates/feature_sanity_schema

# Bundle all templates
bundle-all: bundle-init bundle-feature bundle-feature-sanity
    @echo "All templates have been bundled successfully!"

